name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Start Kubernetes minikube
        uses: medyagh/setup-minikube@master
      - name: Try the Kubernetes cluster
        run: kubectl get nodes
      - name: Build and test
        working-directory: rentalService
        run: |
          export SHELL=/bin/bash
          chmod +x ./gradlew
          ./gradlew build
          eval $(minikube docker-env)
          docker build -f ./Dockerfile -t rentalservice .
          docker images
          cd ..